// Backup pool: 5 trends per category x 8 categories = 40 items.
// Used only when a category has fewer than 2 live trends from the live pipeline.
// Rotated every minute to give variety on refresh.
// Items follow the exact same schema as live Gemini output so UI renders identically.

const mk = (overrides) => ({
  signals: ["Curated"],
  trend_velocity: "stable_high",
  velocity_label: "स्थिर — चर्चा में",
  why_trending: [],
  related_tags: [],
  posted_time: "कुछ घंटे पहले",
  ...overrides,
});

const ge = (q) => `https://news.google.com/search?q=${encodeURIComponent(q)}&hl=hi&gl=IN&ceid=IN:hi`;

export const CATEGORY_POOL = {
  "खेल": [
    mk({
      tag: "#TeamIndia", tagEn: "#TeamIndia",
      description: "टीम इंडिया का अगला सीरीज़ शेड्यूल — फ़ैंस के लिए बड़ी ख़बर",
      category: "खेल", categoryEn: "Sports", heat_score: 88, discussing_count: "3.2 लाख",
      summary: "BCCI ने टीम इंडिया के अगले सीरीज़ का पूरा शेड्यूल जारी कर दिया है। फ़ैंस के बीच टीम सिलेक्शन और प्लेइंग XI को लेकर ज़बरदस्त चर्चा है। कप्तानी, कोचिंग सेटअप और घरेलू सीरीज़ की रणनीति पर एक्सपर्ट्स की राय बँटी हुई है।",
      related_tags: ["#BCCI", "#Cricket", "#India"],
      content_preview: { type: "sports", title: "Team India Schedule: अगले 3 महीनों के सभी मैच", source: "Cricbuzz Hindi", url: ge("Team India schedule") },
    }),
    mk({
      tag: "#ProKabaddi", tagEn: "#ProKabaddi",
      description: "Pro Kabaddi League में आज का बड़ा मुकाबला — UP vs Bengaluru",
      category: "खेल", categoryEn: "Sports", heat_score: 81, discussing_count: "1.8 लाख",
      summary: "प्रो कबड्डी लीग का सीज़न जोरों पर है। आज UP Yoddhas और Bengaluru Bulls के बीच कड़ा मुकाबला होगा। लखनऊ और बेंगलुरु दोनों शहरों से fans की भारी भीड़ स्टेडियम पहुँच रही है।",
      related_tags: ["#Kabaddi", "#PKL", "#Sports"],
      content_preview: { type: "sports", title: "Pro Kabaddi: UP vs Bengaluru लाइव कवरेज", source: "Star Sports Hindi", url: ge("Pro Kabaddi League") },
    }),
    mk({
      tag: "#IndianFootball", tagEn: "#IndianFootball",
      description: "ISL में Mumbai City FC vs Mohun Bagan का धमाकेदार मैच",
      category: "खेल", categoryEn: "Sports", heat_score: 76, discussing_count: "95 हज़ार",
      summary: "Indian Super League में आज Mumbai City FC और Mohun Bagan के बीच टॉप-ऑफ़-द-टेबल मुकाबला है। दोनों टीमें plays-off क्वालिफिकेशन की रेस में हैं। फ़ुटबॉल फ़ैंस के बीच यह मैच काफ़ी चर्चा में है।",
      related_tags: ["#ISL", "#Football", "#MumbaiCity"],
      content_preview: { type: "sports", title: "ISL: Mumbai vs Mohun Bagan प्रीव्यू और प्रेडिक्शन", source: "ESPN India", url: ge("ISL Mumbai Mohun Bagan") },
    }),
    mk({
      tag: "#Hockey", tagEn: "#Hockey",
      description: "Indian Hockey Team ने Asian Champions Trophy में दर्ज की बड़ी जीत",
      category: "खेल", categoryEn: "Sports", heat_score: 74, discussing_count: "78 हज़ार",
      velocity_label: "बढ़ रहा है", trend_velocity: "rising",
      summary: "भारतीय हॉकी टीम ने Asian Champions Trophy के सेमीफाइनल में जापान को 4-2 से हराया है। हरमनप्रीत सिंह के 2 गोल चर्चा का विषय हैं। फ़ाइनल में अब पाकिस्तान या साउथ कोरिया से मुकाबला तय।",
      related_tags: ["#TeamIndia", "#Harmanpreet", "#Asian"],
      content_preview: { type: "sports", title: "Hockey: India ने जीता सेमीफाइनल, फ़ाइनल में जगह पक्की", source: "Hockey India", url: ge("Indian Hockey Asian Champions Trophy") },
    }),
    mk({
      tag: "#WomenInCricket", tagEn: "#WomenInCricket",
      description: "Smriti Mandhana ने तोड़ा बड़ा रिकॉर्ड — सोशल मीडिया पर वायरल",
      category: "खेल", categoryEn: "Sports", heat_score: 72, discussing_count: "1.1 लाख",
      summary: "Smriti Mandhana ने महिला T20 क्रिकेट में सबसे तेज़ 4000 रन बनाने का रिकॉर्ड अपने नाम कर लिया है। उनकी इस उपलब्धि पर देश भर से बधाइयों का तांता लगा है। महिला क्रिकेट को भारत में नया जोश मिल रहा है।",
      related_tags: ["#SmritiMandhana", "#WomensCricket", "#Record"],
      content_preview: { type: "sports", title: "Smriti Mandhana का रिकॉर्ड: सबसे तेज़ 4000 T20 रन", source: "BCCI Women", url: ge("Smriti Mandhana record") },
    }),
  ],

  "मनोरंजन": [
    mk({
      tag: "#BollywoodBoxOffice", tagEn: "#BollywoodBoxOffice",
      description: "इस वीकेंड का बॉक्स ऑफ़िस — कौन सी फ़िल्म आगे, कौन पीछे",
      category: "मनोरंजन", categoryEn: "Entertainment", heat_score: 86, discussing_count: "2.5 लाख",
      summary: "बॉलीवुड बॉक्स ऑफ़िस पर इस वीकेंड कांटे की टक्कर है। तीन बड़ी फ़िल्में release हुई हैं और opening day collection को लेकर ट्रेड एनालिस्ट्स की राय बँटी है। मल्टीप्लेक्स और सिंगल स्क्रीन दोनों में occupancy 70% से ऊपर है।",
      related_tags: ["#Bollywood", "#BoxOffice", "#Movies"],
      content_preview: { type: "entertainment", title: "Box Office: Top 5 फ़िल्में और उनका वीकेंड कलेक्शन", source: "Bollywood Hungama", url: ge("Bollywood box office collection") },
    }),
    mk({
      tag: "#OTTReleases", tagEn: "#OTTReleases",
      description: "इस हफ़्ते Netflix, Prime, Hotstar पर क्या नया देखें",
      category: "मनोरंजन", categoryEn: "Entertainment", heat_score: 82, discussing_count: "1.9 लाख",
      summary: "OTT platforms पर इस हफ़्ते 10+ नई releases हैं — Netflix पर एक नया Hindi web series, Prime Video पर मराठी फ़िल्म, और Hotstar पर क्रिकेट documentary। बिंज-वॉच करने वालों के लिए वीकेंड पैक्ड है।",
      related_tags: ["#Netflix", "#PrimeVideo", "#WebSeries"],
      content_preview: { type: "entertainment", title: "इस हफ़्ते के Top 10 OTT Releases — रिव्यू सहित", source: "Pinkvilla", url: ge("OTT new releases this week India") },
    }),
    mk({
      tag: "#BiggBoss", tagEn: "#BiggBoss",
      description: "Bigg Boss में आज नया twist — कौन हुआ बाहर, कौन बना captain",
      category: "मनोरंजन", categoryEn: "Entertainment", heat_score: 79, discussing_count: "4.2 लाख",
      summary: "Bigg Boss के घर में आज बड़ा drama हुआ। एलिमिनेशन के बाद नए captain का चुनाव हुआ और घर में दोस्त-दुश्मन के नए समीकरण बन गए हैं। Salman Khan के Weekend Ka Vaar episode का इंतज़ार सबको है।",
      related_tags: ["#BiggBoss17", "#SalmanKhan", "#RealityTV"],
      content_preview: { type: "entertainment", title: "Bigg Boss: आज के एपिसोड की पूरी कहानी", source: "Colors TV", url: ge("Bigg Boss latest episode") },
    }),
    mk({
      tag: "#Tollywood", tagEn: "#Tollywood",
      description: "Allu Arjun और Ram Charan की नई फ़िल्म announcement",
      category: "मनोरंजन", categoryEn: "Entertainment", heat_score: 77, discussing_count: "3.1 लाख",
      summary: "तेलुगू सिनेमा के दो सुपरस्टार Allu Arjun और Ram Charan एक साथ बड़े बजट की फ़िल्म में काम करने जा रहे हैं। इस announcement के बाद से Twitter और Instagram पर fans की प्रतिक्रियाएँ वायरल हो रही हैं।",
      related_tags: ["#AlluArjun", "#RamCharan", "#TollywoodNews"],
      content_preview: { type: "entertainment", title: "Allu Arjun-Ram Charan की फ़िल्म: सारी डिटेल", source: "123 Telugu", url: ge("Allu Arjun Ram Charan film") },
    }),
    mk({
      tag: "#Celebrities", tagEn: "#Celebrities",
      description: "Deepika Padukone का नया लुक सोशल मीडिया पर ट्रेंडिंग",
      category: "मनोरंजन", categoryEn: "Entertainment", heat_score: 74, discussing_count: "2.1 लाख",
      summary: "Deepika Padukone ने अपनी अगली फ़िल्म के लिए नया लुक शेयर किया है जो Instagram पर वायरल हो रहा है। 24 घंटे में 5 मिलियन+ likes और स्टाइलिस्ट्स के बीच इस लुक की चर्चा है।",
      related_tags: ["#DeepikaPadukone", "#Bollywood", "#Fashion"],
      content_preview: { type: "entertainment", title: "Deepika Padukone का नया Avatar — Photos Inside", source: "Filmfare", url: ge("Deepika Padukone new look") },
    }),
  ],

  "खबरें": [
    mk({
      tag: "#Parliament", tagEn: "#Parliament",
      description: "संसद के मानसून सत्र में आज कई अहम बिल पास होंगे",
      category: "खबरें", categoryEn: "News", heat_score: 83, discussing_count: "2.7 लाख",
      summary: "संसद का मानसून सत्र चल रहा है। आज दो अहम बिल — डेटा प्रोटेक्शन में amendment और किसानों से जुड़ा एक नया प्रावधान — पास हो सकते हैं। विपक्ष ने hangama का indication दिया है।",
      related_tags: ["#Politics", "#India", "#Bill"],
      content_preview: { type: "news", title: "संसद में आज क्या-क्या होगा? पूरा शेड्यूल", source: "ABP News", url: ge("Indian Parliament session today") },
    }),
    mk({
      tag: "#WeatherUpdate", tagEn: "#WeatherUpdate",
      description: "उत्तर भारत में भारी बारिश का अलर्ट — कई राज्यों में स्कूल बंद",
      category: "खबरें", categoryEn: "News", heat_score: 80, discussing_count: "4.5 लाख",
      velocity_label: "बढ़ रहा है", trend_velocity: "rising",
      summary: "IMD ने उत्तर भारत के 8 राज्यों में अगले 48 घंटों के लिए orange alert जारी किया है। UP, बिहार, राजस्थान, पंजाब में भारी बारिश की संभावना। कई जिलों में स्कूल बंद किए गए हैं, यातायात प्रभावित।",
      related_tags: ["#Weather", "#IMD", "#Rain"],
      content_preview: { type: "news", title: "Weather Alert: किन राज्यों में आज भारी बारिश?", source: "IMD India", url: ge("IMD weather alert India") },
    }),
    mk({
      tag: "#UPIUpdate", tagEn: "#UPIUpdate",
      description: "UPI में नया फीचर लॉन्च — अब credit card भी कर सकेंगे लिंक",
      category: "खबरें", categoryEn: "News", heat_score: 78, discussing_count: "1.5 लाख",
      summary: "NPCI ने UPI में एक नया फ़ीचर जोड़ा है जिसमें अब credit card को सीधे UPI से लिंक किया जा सकेगा। इस से merchant payments में और सुविधा होगी और cashback offers भी मिलेंगे। डिजिटल पेमेंट इकोसिस्टम के लिए बड़ा कदम।",
      related_tags: ["#UPI", "#Digital", "#Fintech"],
      content_preview: { type: "news", title: "UPI Credit Card लिंक: कैसे करें setup", source: "Mint Hindi", url: ge("UPI credit card link feature") },
    }),
    mk({
      tag: "#StockMarket", tagEn: "#StockMarket",
      description: "Sensex 500+ अंक चढ़ा, Nifty नए record high पर",
      category: "खबरें", categoryEn: "News", heat_score: 75, discussing_count: "1.2 लाख",
      summary: "भारतीय शेयर बाज़ार आज नई ऊंचाई पर बंद हुआ। Sensex में 500 से ज़्यादा अंकों की उछाल और Nifty ने नया all-time high छुआ। बैंकिंग और IT स्टॉक्स में सबसे ज़्यादा खरीदारी देखी गई।",
      related_tags: ["#Sensex", "#Nifty", "#Market"],
      content_preview: { type: "news", title: "बाज़ार की क्लोज़िंग रिपोर्ट और कल के संकेत", source: "Moneycontrol Hindi", url: ge("Sensex Nifty closing today") },
    }),
    mk({
      tag: "#Infrastructure", tagEn: "#Infrastructure",
      description: "Vande Bharat के 4 नए routes का ऐलान — आपके शहर पर असर?",
      category: "खबरें", categoryEn: "News", heat_score: 72, discussing_count: "2.3 लाख",
      summary: "Indian Railways ने Vande Bharat Express के 4 नए routes का ऐलान कर दिया है। इनमें Mumbai-Goa, Delhi-Dehradun और दो दूसरे roots शामिल हैं। टिकट booking अगले हफ्ते से शुरू होगी।",
      related_tags: ["#VandeBharat", "#Railways", "#India"],
      content_preview: { type: "news", title: "Vande Bharat नए Routes: टाइमिंग और किराया", source: "Railways India", url: ge("Vande Bharat new routes") },
    }),
  ],

  "स्थानीय": [
    mk({
      tag: "#DelhiPollution", tagEn: "#DelhiPollution",
      description: "दिल्ली में AQI 300 के पार — सरकार ने जारी की advisory",
      category: "स्थानीय", categoryEn: "Local", heat_score: 84, discussing_count: "3.4 लाख",
      summary: "दिल्ली-NCR में air quality फिर से 'very poor' category में पहुँच गया है। AQI 320 दर्ज किया गया। सरकार ने बुज़ुर्गों और बच्चों को घर के अंदर रहने की advisory जारी की है। निर्माण कार्यों पर भी प्रतिबंध लगा।",
      related_tags: ["#Delhi", "#AQI", "#Pollution"],
      content_preview: { type: "news", title: "Delhi AQI Today: अपने इलाके का air quality देखें", source: "CPCB India", url: ge("Delhi AQI pollution today") },
    }),
    mk({
      tag: "#BangaloreTraffic", tagEn: "#BangaloreTraffic",
      description: "बेंगलुरु में traffic chaos — Outer Ring Road पर 4 घंटे की देरी",
      category: "स्थानीय", categoryEn: "Local", heat_score: 76, discussing_count: "1.3 लाख",
      summary: "बेंगलुरु के Outer Ring Road पर आज सुबह भारी जाम लग गया। IT कर्मचारियों को 4 घंटे तक इंतज़ार करना पड़ा। Twitter पर BBMP और traffic police को लेकर लोगों में नाराज़गी है।",
      related_tags: ["#Bangalore", "#Traffic", "#India"],
      content_preview: { type: "news", title: "Bangalore Traffic: कौन-कौन से रास्ते बंद हैं?", source: "Bangalore Mirror", url: ge("Bangalore traffic jam ORR") },
    }),
    mk({
      tag: "#PatnaFlood", tagEn: "#PatnaFlood",
      description: "पटना के निचले इलाकों में बाढ़ का पानी — सरकार राहत में जुटी",
      category: "स्थानीय", categoryEn: "Local", heat_score: 78, discussing_count: "1.8 लाख",
      summary: "गंगा का जलस्तर पटना में खतरे के निशान से ऊपर बह रहा है। निचले इलाकों में पानी घुस गया है, सैकड़ों लोग प्रभावित हैं। SDRF टीमें राहत और बचाव कार्य में जुटी हैं।",
      related_tags: ["#Bihar", "#Patna", "#Ganga"],
      content_preview: { type: "news", title: "Patna Flood Update: कौन-कौन से इलाके प्रभावित", source: "Hindustan Hindi", url: ge("Patna flood Ganga water level") },
    }),
    mk({
      tag: "#KolkataDurgaPuja", tagEn: "#KolkataDurgaPuja",
      description: "कोलकाता में दुर्गा पूजा की तैयारियाँ ज़ोरों पर — pandals तैयार",
      category: "स्थानीय", categoryEn: "Local", heat_score: 79, discussing_count: "2.6 लाख",
      summary: "कोलकाता में दुर्गा पूजा की तैयारियाँ ज़ोरों पर हैं। शहर के बड़े pandals तैयार हो चुके हैं और इस बार theme में Chandrayaan-3 से लेकर पर्यावरण तक शामिल। लाखों श्रद्धालुओं के आने की उम्मीद है।",
      related_tags: ["#Kolkata", "#DurgaPuja", "#Bengal"],
      content_preview: { type: "news", title: "Kolkata Durga Puja: इस बार के Top 10 Pandals", source: "Anandabazar", url: ge("Kolkata Durga Puja pandals") },
    }),
    mk({
      tag: "#ChennaiRains", tagEn: "#ChennaiRains",
      description: "चेन्नई में लगातार बारिश — IT corridors में work from home",
      category: "स्थानीय", categoryEn: "Local", heat_score: 73, discussing_count: "1.1 लाख",
      summary: "चेन्नई में पिछले 2 दिनों से लगातार बारिश हो रही है। IT कंपनियों ने OMR और GST Road पर स्थित ऑफ़िसों में work from home advisory दी है। कई इलाकों में जलभराव की समस्या है।",
      related_tags: ["#Chennai", "#TamilNadu", "#Rain"],
      content_preview: { type: "news", title: "Chennai Rains: स्कूल और दफ़्तर खुले या बंद?", source: "The Hindu Tamil", url: ge("Chennai rains today") },
    }),
  ],

  "त्योहार": [
    mk({
      tag: "#NavratriPrep", tagEn: "#Navratri",
      description: "नवरात्रि की तैयारियाँ शुरू — बाज़ारों में रौनक",
      category: "त्योहार", categoryEn: "Festival", heat_score: 82, discussing_count: "3.5 लाख",
      summary: "नवरात्रि का त्यौहार नज़दीक है और देश भर के बाज़ार सज गए हैं। चूड़ी, साड़ी, गरबा कपड़े, और पूजा सामग्री की दुकानों पर भीड़ है। गुजरात और महाराष्ट्र में garba नाइट्स की advance bookings शुरू।",
      related_tags: ["#Navratri", "#Garba", "#Festival"],
      content_preview: { type: "news", title: "Navratri 2026: तिथि, मुहूर्त और पूजा विधि", source: "Astrosage Hindi", url: ge("Navratri 2026 dates") },
    }),
    mk({
      tag: "#KarvaChauth", tagEn: "#KarvaChauth",
      description: "करवा चौथ 2026 — व्रत की विधि और शुभ मुहूर्त",
      category: "त्योहार", categoryEn: "Festival", heat_score: 75, discussing_count: "2.1 लाख",
      summary: "करवा चौथ का व्रत महिलाओं के लिए विशेष महत्व रखता है। इस बार चांद निकलने का समय और सरगी की पूरी विधि सोशल मीडिया पर ख़ूब search हो रही है। बाज़ारों में मेहंदी और चूड़ियों की भारी मांग।",
      related_tags: ["#Karva", "#Festival", "#Women"],
      content_preview: { type: "news", title: "Karva Chauth: चांद का समय, पूजा सामग्री लिस्ट", source: "AajTak Dharm", url: ge("Karva Chauth 2026 moon time") },
    }),
    mk({
      tag: "#Diwali", tagEn: "#Diwali",
      description: "दिवाली की तैयारियाँ — घर सजाने के नए ट्रेंड्स",
      category: "त्योहार", categoryEn: "Festival", heat_score: 81, discussing_count: "4.3 लाख",
      summary: "दिवाली नज़दीक है और इस बार eco-friendly सजावट का ट्रेंड ज़ोरों पर है। मिट्टी के दीये, हस्तनिर्मित diyas, और sustainable फूल-मालाओं की मांग बढ़ी है। Online retailers पर decoration items की बिक्री 40% बढ़ी।",
      related_tags: ["#Diwali", "#Festival", "#India"],
      content_preview: { type: "news", title: "Diwali 2026: सजावट के 10 बेहतरीन Ideas", source: "Pinkvilla Lifestyle", url: ge("Diwali decoration ideas 2026") },
    }),
    mk({
      tag: "#Eid", tagEn: "#Eid",
      description: "ईद की तैयारियाँ — पुरानी दिल्ली में सेवइयाँ खरीदने की भीड़",
      category: "त्योहार", categoryEn: "Festival", heat_score: 77, discussing_count: "1.9 लाख",
      summary: "ईद का त्यौहार आने को है। दिल्ली, लखनऊ, हैदराबाद के पुराने बाज़ारों में रौनक है। सेवइयाँ, खजूर, मेवे की दुकानों पर लंबी लाइनें। कपड़े और जूतों की बिक्री में 50% की उछाल देखी गई।",
      related_tags: ["#EidMubarak", "#Festival", "#India"],
      content_preview: { type: "news", title: "Eid 2026: सेवइयों की Top 5 Recipes", source: "Aaj Tak Lifestyle", url: ge("Eid 2026 sevai recipe") },
    }),
    mk({
      tag: "#Onam", tagEn: "#Onam",
      description: "केरल में Onam की धूम — साद्या और पुक्कलम तैयार",
      category: "त्योहार", categoryEn: "Festival", heat_score: 71, discussing_count: "1.4 लाख",
      summary: "केरल में Onam के celebrations पूरे ज़ोर पर हैं। घरों में पुक्कलम (फूलों की रंगोली) सज गई है और साद्या (पारंपरिक भोजन) की तैयारियाँ चल रही हैं। Tourism में भी इस वजह से बड़ा उछाल देखा जा रहा है।",
      related_tags: ["#Onam", "#Kerala", "#Festival"],
      content_preview: { type: "news", title: "Onam 2026: साद्या में परोसी जाने वाली 26 dishes", source: "Manorama Hindi", url: ge("Onam Sadhya Kerala") },
    }),
  ],

  "म्यूज़िक": [
    mk({
      tag: "#PunjabiHits", tagEn: "#PunjabiHits",
      description: "Diljit Dosanjh का नया gana रिलीज़ — YouTube पर ट्रेंडिंग #1",
      category: "म्यूज़िक", categoryEn: "Music", heat_score: 85, discussing_count: "3.8 लाख",
      summary: "Diljit Dosanjh का नया punjabi gaana 'Mehndi' आज रिलीज़ हुआ और 6 घंटे में YouTube India trending #1 पर पहुँच गया। उनके fan base में देश-विदेश से लाखों लोग शामिल हैं। Instagram reels पर भी यह song ख़ूब इस्तेमाल हो रहा है।",
      related_tags: ["#Diljit", "#Punjabi", "#Music"],
      content_preview: { type: "entertainment", title: "Diljit Dosanjh New Song: Lyrics और Video", source: "T-Series Punjabi", url: ge("Diljit Dosanjh new song") },
    }),
    mk({
      tag: "#BhojpuriBeats", tagEn: "#Bhojpuri",
      description: "Bhojpuri music का नया हिट — Pawan Singh का song वायरल",
      category: "म्यूज़िक", categoryEn: "Music", heat_score: 78, discussing_count: "5.2 लाख",
      summary: "Pawan Singh का नया Bhojpuri song यूट्यूब पर रिलीज़ हुआ है और 24 घंटे में 10 मिलियन व्यूज़ पार कर गया है। UP, बिहार में इस song पर लाखों रील्स बन रही हैं। Bhojpuri industry में यह साल का सबसे बड़ा hit माना जा रहा है।",
      related_tags: ["#PawanSingh", "#Bhojpuri", "#Music"],
      content_preview: { type: "entertainment", title: "Pawan Singh New Song: Full Video", source: "Wave Music", url: ge("Pawan Singh new bhojpuri song") },
    }),
    mk({
      tag: "#IndiePop", tagEn: "#IndiePop",
      description: "Anuv Jain का नया song — soft rock fans के लिए treat",
      category: "म्यूज़िक", categoryEn: "Music", heat_score: 73, discussing_count: "85 हज़ार",
      summary: "Anuv Jain का नया song 'Mishri' Spotify और YouTube दोनों पर ट्रेंड कर रहा है। Indie music lovers इसे साल का सबसे romantic song बता रहे हैं। Reels पर भी popularity तेज़ी से बढ़ रही है।",
      related_tags: ["#AnuvJain", "#Indie", "#Music"],
      content_preview: { type: "entertainment", title: "Anuv Jain का नया song 'Mishri' Lyrics सहित", source: "Spotify India", url: ge("Anuv Jain new song") },
    }),
    mk({
      tag: "#ClassicalMusic", tagEn: "#ClassicalMusic",
      description: "Pandit Hariprasad Chaurasia का concert — Delhi में आज शाम",
      category: "म्यूज़िक", categoryEn: "Music", heat_score: 68, discussing_count: "32 हज़ार",
      summary: "Legendary flutist Pandit Hariprasad Chaurasia आज शाम Delhi के Kamani Auditorium में concert करेंगे। Tickets sold out। Music lovers और शास्त्रीय संगीत के प्रशंसकों के लिए यह एक यादगार शाम होगी।",
      related_tags: ["#Classical", "#Hariprasad", "#Music"],
      content_preview: { type: "entertainment", title: "Pandit Hariprasad Chaurasia Concert: Details", source: "BookMyShow", url: ge("Hariprasad Chaurasia concert") },
    }),
    mk({
      tag: "#Devotional", tagEn: "#DevotionalMusic",
      description: "Hanuman Chalisa का नया render — सोशल मीडिया पर वायरल",
      category: "म्यूज़िक", categoryEn: "Music", heat_score: 76, discussing_count: "4.1 लाख",
      summary: "एक नए artist द्वारा गाया Hanuman Chalisa का modern render पिछले 3 दिनों से YouTube और Instagram पर वायरल है। 50 मिलियन+ views के साथ यह 2026 का सबसे popular devotional song बन गया है।",
      related_tags: ["#Hanuman", "#Devotional", "#Bhakti"],
      content_preview: { type: "entertainment", title: "Viral Hanuman Chalisa: Full Video और कलाकार के बारे में", source: "T-Series Bhakti", url: ge("Hanuman Chalisa new viral") },
    }),
  ],

  "शिक्षा": [
    mk({
      tag: "#NEETUpdate", tagEn: "#NEETUpdate",
      description: "NEET 2026 की counselling शुरू — caut-off और choice filling",
      category: "शिक्षा", categoryEn: "Education", heat_score: 87, discussing_count: "8.5 लाख",
      summary: "MCC ने NEET-UG 2026 की counselling शुरू कर दी है। Round 1 के लिए choice filling की last date 7 दिन है। 18 लाख से ज़्यादा students ने register किया है। medical college admissions को लेकर देश भर में हलचल।",
      related_tags: ["#NEET", "#MBBS", "#Medical"],
      content_preview: { type: "education", title: "NEET 2026 Counselling: कैसे करें choice filling", source: "MCC India", url: ge("NEET 2026 counselling") },
    }),
    mk({
      tag: "#JEEMains", tagEn: "#JEEMains",
      description: "JEE Main 2026 का application form जारी — last date जल्द",
      category: "शिक्षा", categoryEn: "Education", heat_score: 83, discussing_count: "6.2 लाख",
      summary: "NTA ने JEE Main 2026 के पहले session के लिए application forms जारी कर दिए हैं। Exam pattern में कुछ नए बदलाव हैं और syllabus revised है। IIT aspirants के लिए तैयारी का यह सबसे महत्वपूर्ण समय है।",
      related_tags: ["#JEE", "#IIT", "#Engineering"],
      content_preview: { type: "education", title: "JEE Main 2026: Application Form Direct Link", source: "NTA", url: ge("JEE Main 2026 application") },
    }),
    mk({
      tag: "#UPSCResult", tagEn: "#UPSCResult",
      description: "UPSC Mains का result आउट — interview list जारी",
      category: "शिक्षा", categoryEn: "Education", heat_score: 80, discussing_count: "3.7 लाख",
      summary: "UPSC ने Civil Services Mains का result जारी कर दिया है। Interview के लिए 2500+ candidates select हुए हैं। UP, बिहार, राजस्थान के candidates की संख्या सबसे ज़्यादा है। Toppers की कहानियाँ social media पर inspiration दे रही हैं।",
      related_tags: ["#UPSC", "#IAS", "#CivilServices"],
      content_preview: { type: "education", title: "UPSC Mains Result 2026: Interview की तैयारी कैसे करें", source: "UPSC India", url: ge("UPSC Mains result") },
    }),
    mk({
      tag: "#BankExam", tagEn: "#BankExam",
      description: "SBI PO 2026 notification — 2000 पदों पर भर्ती",
      category: "शिक्षा", categoryEn: "Education", heat_score: 81, discussing_count: "5.8 लाख",
      summary: "SBI ने Probationary Officer के 2000 पदों के लिए notification जारी किया है। Graduate students आवेदन कर सकते हैं। Exam January में होगी और job postings देश भर में होंगी। Banking job के सपने देख रहे youth के लिए बड़ा मौक़ा।",
      related_tags: ["#SBI", "#Banking", "#GovtJob"],
      content_preview: { type: "education", title: "SBI PO 2026: कैसे करें apply, syllabus", source: "SBI Careers", url: ge("SBI PO 2026 notification") },
    }),
    mk({
      tag: "#OnlineLearning", tagEn: "#OnlineLearning",
      description: "Byju's और Unacademy के नए free courses — students को फ़ायदा",
      category: "शिक्षा", categoryEn: "Education", heat_score: 70, discussing_count: "1.3 लाख",
      summary: "Edtech platforms Byju's और Unacademy ने 10वीं-12वीं students के लिए कुछ बड़े subjects के free courses लॉन्च किए हैं। Mathematics, Science, English के lessons अब बिना fee के available हैं। Rural students के लिए यह बड़ी राहत है।",
      related_tags: ["#EdTech", "#OnlineCourses", "#Students"],
      content_preview: { type: "education", title: "Free Online Courses: कैसे करें enroll", source: "Hindustan Hindi Education", url: ge("free online courses India") },
    }),
  ],

  "टेक्नोलॉजी": [
    mk({
      tag: "#AINews", tagEn: "#AI",
      description: "ChatGPT का नया Hindi mode — भारत में हुआ launch",
      category: "टेक्नोलॉजी", categoryEn: "Technology", heat_score: 85, discussing_count: "2.9 लाख",
      summary: "OpenAI ने ChatGPT में full Hindi support add किया है। अब users देवनागरी में सीधे टाइप कर सकते हैं और AI से Hindi में बात कर सकते हैं। Indian tech community में यह बड़ी ख़बर है — productivity tools की दुनिया में नया अध्याय।",
      related_tags: ["#ChatGPT", "#AI", "#OpenAI"],
      content_preview: { type: "news", title: "ChatGPT Hindi: कैसे करें इस्तेमाल", source: "Gadgets Now Hindi", url: ge("ChatGPT Hindi support") },
    }),
    mk({
      tag: "#Smartphones", tagEn: "#Smartphones",
      description: "Samsung Galaxy S26 लॉन्च — Indian price और features",
      category: "टेक्नोलॉजी", categoryEn: "Technology", heat_score: 82, discussing_count: "1.7 लाख",
      summary: "Samsung ने Galaxy S26 series India में लॉन्च कर दी है। Starting price ₹84,999 और top variant ₹1.4 लाख का है। नया AI chip, बेहतर camera और titanium body मुख्य आकर्षण हैं। Pre-orders शुरू हो चुके हैं।",
      related_tags: ["#Samsung", "#Galaxy", "#Smartphone"],
      content_preview: { type: "news", title: "Samsung Galaxy S26 India Price और Features", source: "Gadgets360", url: ge("Samsung Galaxy S26 India") },
    }),
    mk({
      tag: "#Fintech", tagEn: "#Fintech",
      description: "Paytm का नया feature — अब EMI पर खरीदें smartphone",
      category: "टेक्नोलॉजी", categoryEn: "Technology", heat_score: 74, discussing_count: "1.1 लाख",
      summary: "Paytm ने एक नया feature launch किया है जिसमें users smartphones को 0% interest EMI पर खरीद सकते हैं — वो भी credit card के बिना। यह सुविधा Tier 2-3 शहरों के users के लिए ख़ास तौर पर बनाई गई है।",
      related_tags: ["#Paytm", "#EMI", "#Fintech"],
      content_preview: { type: "news", title: "Paytm EMI: कैसे ख़रीदें smartphone बिना card", source: "ET Tech", url: ge("Paytm EMI smartphone") },
    }),
    mk({
      tag: "#Startups", tagEn: "#Startups",
      description: "Indian startup Zepto ने जुटाए $500M — IPO की तैयारी",
      category: "टेक्नोलॉजी", categoryEn: "Technology", heat_score: 79, discussing_count: "2.4 लाख",
      summary: "Quick commerce startup Zepto ने $500 million की नई funding जुटाई है। Valuation $5 billion से ऊपर पहुँच गई है। कंपनी अगले साल IPO लाने की तैयारी कर रही है। Quick delivery industry में competition बढ़ रहा है।",
      related_tags: ["#Zepto", "#Startup", "#Funding"],
      content_preview: { type: "news", title: "Zepto Funding: $500M की डील का पूरा विश्लेषण", source: "Inc42", url: ge("Zepto funding 500 million") },
    }),
    mk({
      tag: "#5GIndia", tagEn: "#5G",
      description: "Jio और Airtel ने Tier-3 शहरों में 5G expand किया",
      category: "टेक्नोलॉजी", categoryEn: "Technology", heat_score: 72, discussing_count: "1.5 लाख",
      summary: "Jio और Airtel ने अपनी 5G coverage को 200 नए शहरों में expand कर दिया है। ज़्यादातर Tier 2-3 शहर शामिल हैं। UP, बिहार, MP के users को अब high-speed connectivity मिलेगी। Internet speeds में 5-10x का सुधार expected है।",
      related_tags: ["#5G", "#Jio", "#Airtel"],
      content_preview: { type: "news", title: "5G Coverage Map: आपका शहर list में है?", source: "TelecomTalk", url: ge("Jio Airtel 5G expansion cities") },
    }),
  ],
};
